TEXTURES = {
    [1] = {
        '*_dirt1*', '*scrub1*', '*oldrun*', '*panelconc*', '*ripplsand*', '*dirtgrassmix*', '*grassdeadbrn256*', '*grasstype5*', '*heavygrass*',
        '*grassbrn', '*grassbrn_lod', '*grass2scrub*', '*grass2dirt*', '*desgrasand*', '*grass_gen*', '*grass_lod*', '*dirt64b2*', 'Grass',
        'Grass_128*', 'Grass_lod', '*sandgrnd*', '*grass_dry*', '*yardgras*', '*vegasgolflod*', 'newcrop3', 'desgreengrassmix', '*con2sand*',
        '*grassdry*', '*vgn_ground*', '*drvin_ground*', '*grasslod*', '*brngrass*', '*desgrassbrnLOD*', '*vgsEcoast*', '*vgwestbildlod*',
        '*sfn_grass1*', '*asfnsjm6*', '*asfnsjm94*', '*asfnsjm9i*', '*asfnsjm93*', '*asfnsjm9h*', '*grass4dirty*', '*grasstype4', '*oldflowerb*',
        '*grassbrn_grn*', '*desertgryard*', '*dirt2gygras*', '*sl_sfn*', '*grassdead1*', '*grasstype10*', '*grasstype4_10*', '*grasstype4_forest*',
        '*desertgravelgrass*', '*dirtKB_64*', '*grassdeep1*', '*desmudgrass*', '*grasspatch*', '*Grass_path*',
        'des_dirt2stones*', 'des_dirt2grass*', 'desgreengrass', 'grasstype7*', 'grassdirtblend', 'compurch_lod', '*church_dirt*', '*grasstype3*',
        '*grasstype4-3*', 'sw_grass01a*', 'sw_grassB01*', 'sw_grass01', 'sw_grass01LOD', 'sw_dirt01*', 'sw_crops*', 'grassgrnbrnx*',
        '*forestfloorblend*', '*forestfloorbranch*', '*forestfloor256*', '*forestfloor256L*', '*forestfloorgrass*', '*mounttrail*',
        '*stonesgrass*', '*sw_stones*', '*mountainskree*', 'stones256', 'grass10_stones256', '*grass10dir*', '*mountdirt2grass', '*mountdirt',
        '*grassbrn2rock*', '*grasstype4_mudblend*', 'desmud', 'forestfloor_sones*', 'dirtblendlit*', 'brngrss2stones*',
        '*grassdead1*', '*forestfloor3', '*forestfloor3_for*', '*dirt2ded*', '*dirtgravel*', '*_dirt2', '*_dirt2lod', 'des_dirt2blend*',
        '*rocktq128_dirt', '*rocktq128_forest*', '*rocktq128_grass*', '*descliff*', 'desertstones256grass', '*cuntbrncliff*', '*lasclif*', '*dirtgravel*', '*roadedge*',
        'desgreengrassmixlod'
    },
    [2] = {'des_dirttrack1'},
    [6] = {'des_dirttrackl'},
    [18] = {'des_dirttrack1r'},
    [19] = {'des_dirttrackx'},
    [26] = {'pavebsand256', 'pavebsandend'},
    [3] = {'*redrockmid*'},
    [4] = {'*redrockbot*'},
    [5] = {
        '*_1line*', '*des_road1*', '*_2line*', '*_lines*', '*dt_road*', '*Tar_vent*', '*Tar_free*', '*Tar_LeftR*', '*cn2_troad*', '*countryroads*',
        '*sjmlas2lod5n', '*snpdwargrn*', '*1linefree*', '*lawnroad*'
    },
    [7] = {'*rocky*', '*sm_rock2*', '*redrock2*', '*redrock1*'},
    [10] = {'*des_bush2*'},
    [13] = {
        'hiwayinside5_256', '*sl_laefreeway*', '*freewaylae*', '*lawroad*', '*lawhiway*', '*sjmloda991*', '*dualroad*', '*snpedtest*', '*_1lineX*', '*roadverge*',
        '*laneverge*', '*hroadlod*', '*townroad*', '*roadgrassbl*', '*roadwide*', '*LODfreeway*', '*MelroadL*', '*roadLOD*', '*bridgroad*',
        '*freewayroads*', '*lastroadbug*', '*free2road*', '*lanLODroad*', '*sjmlaelodf995*', '*sjmlaelodf5', '*craproad1*', '*lae2roadiv*',
        '*roadcoast5*', '*roadcoast6*', '*freewayfae*', '*lae2rdcst*', '*ws_freeway3*', '*lanefreeway*', '*road5*', '*sfroad2*', '*roadnew*',
        '*greypavroad*', '*hiwayout*', '*hiwaymid*', '*hiwayend*', '*vegasroad*', '*dirtyroad*', '*roadirt*', '*road01_lod*', '*road02_lod*',
        '*road02c_lod*', '*road02b_lod*', '*road02d_lod*', '*roadjunc*', '*junction*', '*dt_road*', '*gasroad*', '*striproad*', '*roadgas*',
        '*lae2rdfuk*', '*freewaylaw2*', '*hiwaygras_lod*', '*roads_sfnLOD*', '*LOD_mountainroad*'
    },
    [14] = {'*traintrax*'},
    [15] = {'*traingrav*', 'des_crackeddirt1'},
    [22] = {'*mountroad*', '*_dirt2track', 'des_dirt2trackr'},
    [23] = {'*_dirt2 t*'},
    [27] = {'*rockhole*'},
    [29] = {'*rockdetail2*', 'rocktbrn128*', '*mountrock*', '*golf_grassrock*', '*asfnsjm9zb*', '*vgs_rockmid*', '*sw_rockgrass1*', '*rock_country*'},
    [30] = {'*rock2grgrass*', '*sw_rockgrassB*', '*vgs_rockbot*'},
    [31] = {'*sfn_rocktbrn*'},
    [32] = {'desmudtrail', 'dirttracksgrass256', 'dirttracksgrass256lod', 'sw_farmroad01', 'sw_farmroad01lod', 'dirttracksforest'},
    [36] = {'*railwy*'},
    [38] = {'*bonyrd_skin*'},
    [39] = {'*josh_leaf*'},
    [33] = {'desgreengrasstrckend'},
    [40] = {'*josh_bark*'},
    [41] = {'*des_bush1*'},
    [42] = {'*des_bush3*'},
    [44] = {'*sfncn_rockgrass3*', 'rocktbrn_*'},
    [45] = {'*rocktq128', '*rocktq128ble*', '*yelrock*'},
    [57] = {'*mountdirt2forest*'},
    [62] = {'sw_sandgrass'},
    [65] = {'*forest_rocks*', '*grasstype4blnd*', 'desmuddesgrsblend'},
    [72] = {'sw_sandgrass4'},
    [78] = {'BLOCK*', 'brick*', '*sam_camo*'},
    [79] = {'*desertstones256for*'},
    [80] = {'*gb_rug01*'},
    ['pedra'] = {'desertstones256', 'desgrns256'},
}
