UTILS = exports['stoneage_utils']

configs = {
    timeToDestroySack = {
        min = UTILS:minutes(10),
        max = UTILS:minutes(15),
    },
    lootSettings = {
        ['military-barrel'] = {
            modelID = 1218,
            maxHealth = 2000,
            zOffset = 0.4,
            respawnTime = {UTILS:minutes(20), UTILS:minutes(25)},
            chancesToSpawn = 100,
        },
        ['military-box'] = {
            modelID = 2975,
            maxSlots = 35,
            zOffset = -0.4,
            respawnTime = {UTILS:minutes(30), UTILS:minutes(40)},
            chancesToSpawn = 100,
        },
        ['default-barrel'] = {
            modelID = 935,
            maxHealth = 1000,
            zOffset = -0.4,
            respawnTime = {UTILS:minutes(15), UTILS:minutes(35)},
            chancesToSpawn = 100,
        },
        ['flammable-barrel'] = {
            modelID = 1225,
            maxHealth = 1500,
            zOffset = -0.4,
            respawnTime = {UTILS:minutes(15), UTILS:minutes(35)},
            chancesToSpawn = 20,
        },
        ['industrial-barrel'] = {
            modelID = 3632,
            maxHealth = 1500,
            zOffset = -0.4,
            respawnTime = {UTILS:minutes(20), UTILS:minutes(40)},
            chancesToSpawn = 100,
        },
        ['default-box'] = {
            modelID = 1558,
            maxSlots = 35,
            zOffset = -0.2,
            respawnTime = {UTILS:minutes(30), UTILS:minutes(50)},
            chancesToSpawn = 100,
        },
    },
}

possibleLootPoints = {
    [3593] = {
        possibleLootType = {'default-box', 'default-barrel', 'default-barrel'},
        possibleLootPositions = {
            [1] = {0, 0, 0.55},
            [2] = {2, 2, 0.55},
            [3] = {-2, -2, 0.55},
        },
    },
    [12957] = {
        possibleLootType = {'default-box', 'default-barrel', 'flammable-barrel'},
        possibleLootPositions = {
            [1] = {0, 0.5, 0.65},
            [2] = {2, -1.75, 0.25},
            [3] = {-1.75, 1.5, 0.25},
        },
    },
    [3594] = {
        possibleLootType = {'default-barrel', 'default-barrel'},
        possibleLootPositions = {
            [1] = {1.75, -1.5, 0.5},
            [2] = {-1.75, 1.5, 0.5},
        },
    },
    [18451] = {
        possibleLootType = {'default-barrel', 'flammable-barrel', 'default-barrel'},
        possibleLootPositions = {
            [1] = {2, -1.5, 0.5},
            [2] = {1, 2.3, 0.3},
            [3] = {-2, 2, 0.5},
        },
    },
    [1440] = {
        possibleLootType = {'default-barrel', 'default-barrel'},
        possibleLootPositions = {
            [1] = {0, -1.5, 0.5},
            [2] = {0.5, 1.5, 0.5},
        },
    },
}

decorations = {
    {
        model = 849,
        offsets = {2, {-1, 2}, -0.5},
    },
    {
        model = 2840,
        offsets = {-2, {-2, 2}, -0.5},
    },
    {
        model = 2866,
        offsets = {-2, {-2, 2}, -0.5},
    },
    {
        model = 800,
        scale = 0.3,
        offsets = {-2, {-2, 2}, -0.5},
    },
    {
        model = 800,
        scale = 0.3,
        offsets = {2, {-1, 1}, -0.5},
    },
    {
        model = 801,
        scale = 0.5,
        offsets = {2, {-2, 2}, -0.5},
    },
    {
        model = 808,
        scale = 0.5,
        offsets = {-2, {-2, 2}, -0.5},
    },
    {
        model = 819,
        scale = 0.5,
        offsets = {-2, {-3, 3}, -0.5},
    }
}

lootPointsFromModel = {
    [935] = 'default-barrel',
    [1218] = 'military-barrel',
    [2975] = 'military-box',
    [1225] = 'flammable-barrel',
    [3632] = 'industrial-barrel',
    [1558] = 'default-box',
}

possibleLoots = {
    ['default-barrel'] = {
        {'Clock', 15},
        {'Duct Tape', 15},
        {'Gears', 15},
        {'Rope', 15},
        {'Sewing Kit', 15},
        {'Sheet Metal', 15},
        {'Animal Fat', 5},
        {'Toolbox', 15},
        {'Paper', 15},
        {'Sand', 15},
        {'Scrap Metal', 30},
        {'Metal Pipe', 15},
        {'Metal Spring', 10},
        {'Road Signs', 15},
        {'Battery', 18},
        {'Cloth', 15},
        {'Empty Bottle', 15},
        {'Empty Gallon', 15},
        {'Fosforo', 15},
        {'Sticks', 15},
        {'Tech Parts', 3},
        {'Metal de Alta', 3},
        {'Tire', 13},
        {'Gallon', 13},
        {'Beans Can', 13},
        {'Potato', 4},
        {'Corn', 4},
        {'Pumpkin', 4},
        {'Mask', 11},
        {'Water', 12},
        {'Pickaxe', 13},
        {'Hatchet', 13},
        {'Raw Meat', 10},
        {'Seed Corn', 10},
        {'Seed Potato', 10},
        {'Seed Pumpkin', 10},
        {'Animal Fat', 5},
        {'Bolt', 50},
        {'Helmet', 50},
        {'Vest', 50},
        {'Blood Kit', 4},
        {'M39', 50},
        {'AK', 50},
        {'LR-300', 50},
        {'MP5', 60},
        {'Thompson', 60},
        {'Sniper Ammo', 40},
        {'KeyCard', 50},
        
    },
    ['industrial-barrel'] = {
        {'Engine', 10},
        {'Parts', 10},
        {'Tire', 10},
        {'Vehicle Battery', 20},
        {'Toolbox', 20},
        {'Empty Gallon', 20},
        {'Camera', 10},
        {'Battery', 20},
        {'Tech Parts', 1},
        {'Scrap Metal', 3},
        {'Sheet Metal', 3},
        {'Metal Spring', 3},
        {'Road Signs', 3},
    },
    ['flammable-barrel'] = {
        {'Gallon', 20},
        {'Empty Gallon', 40},
        {'Animal Fat', 30},
        {'Coal', 10},
    },
    ['default-box'] = {
        {'Water', 20},
        {'Radial', 8},
        {'Mask', 7},
        {'Chainsaw', 8},
        {'JackHammer', 10},
        {'Hatchet', 20},
        {'Pickaxe', 20},
        {'Camera', 15},
        {'Gears', 20},
        {'Metal Pipe', 20},
        {'Road Signs', 25},
        {'Tech Parts', 2},
        {'Sheet Metal', 4},
        {'Seed Corn', 8},
        {'Sheet Potato', 8},
        {'Sheet Pumpkin', 8},
        {'Toolbox', 25},
        {'Animal Fat', 10},
        {'Apple', 10},
        {'Beans Can', 10},
        {'Corn', 10},
        {'Potato', 10},
        {'Pumpkin', 10},
        {'M92', 10},
        {'Shovel', 8},
        {'Double Barreled', 8},
        {'Pump', 8},
        {'KeyCard', 7},
        {'Sewing Kit', 7},
        {'Coal', 7},
        {'Pump', 4},
        {'Spas', 4},
        {'Custom SMG', 5},
        {'M92', 25},
        {'Python', 15},
        {'Bolt', 50},
        {'Blood Kit', 4},
        {'Helmet', 50},
        {'Vest', 50},
        {'M39', 50},
        {'AK', 50},
        {'LR-300', 50},
        {'MP5', 60},
        {'Thompson', 60},
        {'Sniper Ammo', 40},
        {'KeyCard', 50},
    },
    ['military-box'] = {
        {'L96', 50},
        {'Bolt', 50},
        {'Helmet', 50},
        {'Vest', 50},
        {'M39', 50},
        {'AK', 50},
        {'LR-300', 50},
        {'MP5', 60},
        {'Thompson', 60},
        {'Sniper Ammo', 40},
        {'KeyCard', 50},
        {'Pump', 20},
        {'Spas', 15},
        {'Double Barreled', 20},
        {'Custom SMG', 15},
        {'M92', 25},
        {'Python', 15},
        {'Revolver', 20},
        {'Sentry Ammo', 10},
        {'Radial', 13},
        -- {'Flamethrower', 3},
        {'Scrap Metal', 3},
        {'Tech Parts', 3},
        {'Blood Kit', 4},
        {'Camera', 3},
        {'Metal de Alta', 3},
        {'Road Signs', 3},
    },
    ['military-barrel'] = {
        {'Radial', 4},
        {'Blood Kit', 4},
        {'Mask', 4},
        {'M92', 10},
        {'Python', 10},
        {'Camera', 3},
        {'Custom SMG', 3},
        {'Revolver', 20},
        {'Scrap Metal', 5},
        {'KeyCard', 4},
        {'Python', 10},
        {'Spas', 10},
        {'Pump', 15},
        {'Scrap Metal', 3},
        {'Gears', 6},
        {'Sub Ammo', 6},
        {'Chainsaw', 6},
        {'JackHammer', 6},
        {'Tech Parts', 8},
        {'Cloth', 5},
        {'Duct Tape', 5},
        {'Sewing Kit', 5},
        {'Sentry Ammo', 2},
        {'Road Signs', 2},
        {'Camera', 2},
        {'Coal', 2},
        {'C4', 4},
        {'Rocket Launcher', 2},
        {'Rocket Launcher Ammo', 1},
        {'Satchel', 5},
        {'L96', 50},
        {'Bolt', 50},
        {'Helmet', 50},
        {'Vest', 50},
        {'M39', 50},
        {'AK', 50},
        {'LR-300', 50},
        {'MP5', 60},
        {'Thompson', 60},
        {'Sniper Ammo', 40},
        {'KeyCard', 50},
    },
}

Roupas = {
    {'Calca 1', 1},
    {'Calca 2', 1},
    {'Calca 3', 1},
    {'Calca 4', 1},
    {'Calca 5', 1},
    {'Calca 6', 1},
    {'Calca 7', 1},
    {'Calca 8', 1},
    {'Calca 9', 1},
    {'Calca 10', 1},
    {'Calca 11', 1},
    {'Sapato 1', 1},
    {'Sapato 2', 1},
    {'Sapato 3', 1},
    {'Sapato 4', 1},
    {'Sapato 5', 1},
    {'Sapato 6', 1},
    {'Sapato 7', 1},
    {'Chapeu 1', 1},
    {'Chapeu 2', 1},
    {'Chapeu 3', 1},
    {'Chapeu 4', 1},
    {'Chapeu 5', 1},
    {'Chapeu 6', 1},
    {'Chapeu 7', 1},
    {'Camisa 1', 1},
    {'Camisa 2', 1},
    {'Camisa 3', 1},
    {'Camisa 4', 1},
    {'Camisa 5', 1},
    {'Camisa 6', 1},
    {'Camisa 7', 1},
    {'Camisa 8', 1},
    {'Camisa 9', 1},
    {'Camisa 10', 1},
    {'Camisa 11', 1},
    {'Camisa 12', 1},
    {'Camisa 13', 1},
    {'Camisa 14', 1},
    {'Camisa 11', 1},
}

for type, v in pairs(possibleLoots) do
    table.sort(v, function(a, b)
        return a[2] < b[2]
    end)
end
