POSSIBLE_MESSAGES = {[[CANSADO DE TER QUE FARMAR PARA CONSEGUIR LEVEL PARA PODER CONSTRUIR UMA BASE GRANDE?
#FFFF00ADQUIRA NOSSA FILIAÇÃO PREMIUM#BFB9AF, ALÉM DE AJUDAR O SERVIDOR VOCÊ RECEBERÁ VANTAGENS,
COMO: RESPAWNAR NA CAMA COM MENOS TEMPO VIVO, TER MAIS SLOTS DE CONSTRUÇÃO DE BASE, ETC.
]], [[PRECISANDO DE AJUDA? ENTRE EM NOSSO DISCORD E ABRA UM TICKET, VOCÊ SERÁ ATENDIDO O MAIS
RÁPIDO POSSÍVEL.]], [[ESTE SERVIDOR É DESENVOLVIDO POR UMA EQUIPE COMPOSTA PELOS SEGUINTES MEMBROS:

ADMINISTRAÇÃO GERAL:

DESENVOLVIMENTO:

VETERAN MODERATOR:

AGRADECIMENTOS ESPECIAIS PARA:

]]}
