-- PALITO
assignReplace(4564, {file = 'objects/bases/0(palito)/1_foundation', custom = {txd = 'objects/bases/0(palito)/texture'}})
assignReplace(4602, {file = 'objects/bases/0(palito)/2_foundation_triangular', custom = {txd = 'objects/bases/0(palito)/texture'}})
assignReplace(4188, {file = 'objects/bases/0(palito)/3_foundation_div', custom = {txd = 'objects/bases/0(palito)/texture'}})
assignReplace(4141, {file = 'objects/bases/0(palito)/4_parede', custom = {txd = 'objects/bases/0(palito)/texture'}})
assignReplace(4079, {file = 'objects/bases/0(palito)/5_parede_div', custom = {txd = 'objects/bases/0(palito)/texture'}})
assignReplace(5403, {file = 'objects/bases/0(palito)/6_parede_janela_a', custom = {txd = 'objects/bases/0(palito)/texture'}})
assignReplace(5452, {file = 'objects/bases/0(palito)/7_parede_janela_f', custom = {col = 'objects/bases/0(palito)/4_parede', txd = 'objects/bases/0(palito)/texture'}})
assignReplace(4593, {file = 'objects/bases/0(palito)/8_parede_porta', custom = {txd = 'objects/bases/0(palito)/texture'}})
assignReplace(4576, {file = 'objects/bases/0(palito)/9_escada', custom = {txd = 'objects/bases/0(palito)/texture'}})
assignReplace(5767, {file = 'objects/bases/0(palito)/10_portao', custom = {col = 'objects/bases/0(palito)/4_parede', txd = 'objects/bases/0(palito)/texture'}})
assignReplace(5708, {file = 'objects/bases/0(palito)/11_portao_aberto_1', custom = {col = false, txd = 'objects/bases/0(palito)/texture'}})
assignReplace(6371, {file = 'objects/bases/0(palito)/11_portao_aberto_2', custom = {col = false, txd = 'objects/bases/0(palito)/texture'}})
assignReplace(6388, {file = 'objects/bases/0(palito)/12_porta', custom = {txd = 'objects/bases/0(palito)/12_porta'}})
assignReplace(6389, {file = 'objects/bases/0(palito)/13_teto', custom = {txd = 'objects/bases/0(palito)/texture'}})
assignReplace(4101, {file = 'objects/bases/0(palito)/14_teto_div', custom = {txd = 'objects/bases/0(palito)/texture'}})
assignReplace(4002, {file = 'objects/bases/0(palito)/15_teto_escada', custom = {txd = 'objects/bases/0(palito)/texture'}})
assignReplace(4019, {file = 'objects/bases/0(palito)/16_teto_triangular', custom = {txd = 'objects/bases/0(palito)/texture'}})

-- MADEIRA
assignReplace(1934, {file = 'objects/bases/1(madeira)/1_foundation', custom = {txd = 'objects/bases/1(madeira)/texture'}})
assignReplace(1898, {file = 'objects/bases/1(madeira)/2_foundation_triangular', custom = {txd = 'objects/bases/1(madeira)/texture'}})
assignReplace(1022, {file = 'objects/bases/1(madeira)/3_foundation_div', custom = {txd = 'objects/bases/1(madeira)/texture'}})
assignReplace(3455, {file = 'objects/bases/1(madeira)/4_parede', custom = {txd = 'objects/bases/1(madeira)/texture'}})
assignReplace(2384, {file = 'objects/bases/1(madeira)/5_parede_div', custom = {txd = 'objects/bases/1(madeira)/texture'}})
assignReplace(1782, {file = 'objects/bases/1(madeira)/6_parede_janela_a', custom = {txd = 'objects/bases/1(madeira)/texture'}})
assignReplace(2052, {file = 'objects/bases/1(madeira)/7_parede_janela_f', custom = {col = 'objects/bases/1(madeira)/4_parede', txd = 'objects/bases/1(madeira)/texture'}})
assignReplace(10031, {file = 'objects/bases/1(madeira)/8_parede_porta', custom = {txd = 'objects/bases/1(madeira)/texture'}})
assignReplace(2276, {file = 'objects/bases/1(madeira)/9_escada', custom = {txd = 'objects/bases/1(madeira)/texture'}})
assignReplace(2958, {file = 'objects/bases/1(madeira)/10_portao', custom = {col = 'objects/bases/1(madeira)/4_parede', txd = 'objects/bases/1(madeira)/texture'}})
assignReplace(1621, {file = 'objects/bases/1(madeira)/11_portao_aberto_1', custom = {col = false, txd = 'objects/bases/1(madeira)/texture'}})
assignReplace(1622, {file = 'objects/bases/1(madeira)/11_portao_aberto_2', custom = {col = false, txd = 'objects/bases/1(madeira)/texture'}})
assignReplace(2282, {file = 'objects/bases/1(madeira)/12_porta', custom = {txd = 'objects/bases/1(madeira)/12_porta'}})
assignReplace(10030, {file = 'objects/bases/1(madeira)/13_teto', custom = {txd = 'objects/bases/1(madeira)/texture'}})
assignReplace(2102, {file = 'objects/bases/1(madeira)/14_teto_div', custom = {txd = 'objects/bases/1(madeira)/texture'}})
assignReplace(2272, {file = 'objects/bases/1(madeira)/15_teto_escada', custom = {txd = 'objects/bases/1(madeira)/texture'}})
assignReplace(2404, {file = 'objects/bases/1(madeira)/16_teto_triangular', custom = {txd = 'objects/bases/1(madeira)/texture'}})

-- PEDRA
assignReplace(8242, {file = 'objects/bases/2(pedra)/1_foundation', custom = {txd = 'objects/bases/2(pedra)/texture'}})
assignReplace(2405, {file = 'objects/bases/2(pedra)/2_foundation_triangular', custom = {txd = 'objects/bases/2(pedra)/texture'}})
assignReplace(1783, {file = 'objects/bases/2(pedra)/3_foundation_div', custom = {txd = 'objects/bases/2(pedra)/texture'}})
assignReplace(7490, {file = 'objects/bases/2(pedra)/4_parede', custom = {txd = 'objects/bases/2(pedra)/texture'}})
assignReplace(4587, {file = 'objects/bases/2(pedra)/5_parede_div', custom = {txd = 'objects/bases/2(pedra)/texture'}})
assignReplace(1903, {file = 'objects/bases/2(pedra)/6_parede_janela_a', custom = {txd = 'objects/bases/2(pedra)/texture'}})
assignReplace(7521, {file = 'objects/bases/2(pedra)/7_parede_janela_f', custom = {txd = 'objects/bases/2(pedra)/texture'}})
assignReplace(7513, {file = 'objects/bases/2(pedra)/8_parede_porta', custom = {txd = 'objects/bases/2(pedra)/texture'}})
assignReplace(2260, {file = 'objects/bases/2(pedra)/9_escada', custom = {txd = 'objects/bases/2(pedra)/texture'}})
assignReplace(7531, {file = 'objects/bases/2(pedra)/10_portao', custom = {txd = 'objects/bases/2(pedra)/texture'}})
assignReplace(1518, {file = 'objects/bases/2(pedra)/11_portao_aberto_1', custom = {col = false, txd = 'objects/bases/2(pedra)/texture'}})
assignReplace(1944, {file = 'objects/bases/2(pedra)/11_portao_aberto_2', custom = {col = false, txd = 'objects/bases/2(pedra)/texture'}})
assignReplace(1546, {file = 'objects/bases/2(pedra)/12_porta', custom = {txd = 'objects/bases/2(pedra)/12_porta'}})
assignReplace(1839, {file = 'objects/bases/2(pedra)/13_teto', custom = {txd = 'objects/bases/2(pedra)/texture'}})
assignReplace(1851, {file = 'objects/bases/2(pedra)/14_teto_div', custom = {txd = 'objects/bases/2(pedra)/texture'}})
assignReplace(2258, {file = 'objects/bases/2(pedra)/15_teto_escada', custom = {txd = 'objects/bases/2(pedra)/texture'}})
assignReplace(1852, {file = 'objects/bases/2(pedra)/16_teto_triangular', custom = {txd = 'objects/bases/2(pedra)/texture'}})

-- FERRO
assignReplace(7526, {file = 'objects/bases/3(ferro)/1_foundation', custom = {txd = 'objects/bases/3(ferro)/texture'}})
assignReplace(2410, {file = 'objects/bases/3(ferro)/2_foundation_triangular', custom = {txd = 'objects/bases/3(ferro)/texture'}})
assignReplace(1790, {file = 'objects/bases/3(ferro)/3_foundation_div', custom = {txd = 'objects/bases/3(ferro)/texture'}})
assignReplace(7528, {file = 'objects/bases/3(ferro)/4_parede', custom = {txd = 'objects/bases/3(ferro)/texture'}})
assignReplace(2820, {file = 'objects/bases/3(ferro)/5_parede_div', custom = {txd = 'objects/bases/3(ferro)/texture'}})
assignReplace(5781, {file = 'objects/bases/3(ferro)/6_parede_janela_a', custom = {txd = 'objects/bases/3(ferro)/texture'}})
assignReplace(6875, {file = 'objects/bases/3(ferro)/7_parede_janela_f', custom = {txd = 'objects/bases/3(ferro)/texture'}})
assignReplace(6134, {file = 'objects/bases/3(ferro)/8_parede_porta', custom = {txd = 'objects/bases/3(ferro)/texture'}})
assignReplace(2123, {file = 'objects/bases/3(ferro)/9_escada', custom = {txd = 'objects/bases/3(ferro)/texture'}})
assignReplace(8499, {file = 'objects/bases/3(ferro)/10_portao', custom = {txd = 'objects/bases/3(ferro)/texture'}})
assignReplace(1613, {file = 'objects/bases/3(ferro)/11_portao_aberto_1', custom = {col = false, txd = 'objects/bases/3(ferro)/texture'}})
assignReplace(1614, {file = 'objects/bases/3(ferro)/11_portao_aberto_2', custom = {col = false, txd = 'objects/bases/3(ferro)/texture'}})
assignReplace(2096, {file = 'objects/bases/3(ferro)/12_porta', custom = {txd = 'objects/bases/3(ferro)/12_porta'}})
assignReplace(1970, {file = 'objects/bases/3(ferro)/13_teto', custom = {txd = 'objects/bases/3(ferro)/texture'}})
assignReplace(1969, {file = 'objects/bases/3(ferro)/14_teto_div', custom = {txd = 'objects/bases/3(ferro)/texture'}})
assignReplace(2121, {file = 'objects/bases/3(ferro)/15_teto_escada', custom = {txd = 'objects/bases/3(ferro)/texture'}})
assignReplace(1968, {file = 'objects/bases/3(ferro)/16_teto_triangular', custom = {txd = 'objects/bases/3(ferro)/texture'}})

-- BLINDADO
assignReplace(4001, {file = 'objects/bases/4(blindado)/1_foundation', custom = {txd = 'objects/bases/4(blindado)/texture'}})
assignReplace(4022, {file = 'objects/bases/4(blindado)/2_foundation_triangular', custom = {txd = 'objects/bases/4(blindado)/texture'}})
assignReplace(2347, {file = 'objects/bases/4(blindado)/3_foundation_div', custom = {txd = 'objects/bases/4(blindado)/texture'}})
assignReplace(2864, {file = 'objects/bases/4(blindado)/4_parede', custom = {txd = 'objects/bases/4(blindado)/texture'}})
assignReplace(5426, {file = 'objects/bases/4(blindado)/5_parede_div', custom = {txd = 'objects/bases/4(blindado)/texture'}})
assignReplace(10951, {file = 'objects/bases/4(blindado)/6_parede_janela_a', custom = {txd = 'objects/bases/4(blindado)/texture'}})
assignReplace(8954, {file = 'objects/bases/4(blindado)/7_parede_janela_f', custom = {txd = 'objects/bases/4(blindado)/texture'}})
assignReplace(17520, {file = 'objects/bases/4(blindado)/8_parede_porta', custom = {txd = 'objects/bases/4(blindado)/texture'}})
assignReplace(7529, {file = 'objects/bases/4(blindado)/9_escada', custom = {txd = 'objects/bases/4(blindado)/texture'}})
assignReplace(7234, {file = 'objects/bases/4(blindado)/10_portao', custom = {txd = 'objects/bases/4(blindado)/texture'}})
assignReplace(9595, {file = 'objects/bases/4(blindado)/11_portao_aberto_1', custom = {col = false, txd = 'objects/bases/4(blindado)/texture'}})
assignReplace(9523, {file = 'objects/bases/4(blindado)/11_portao_aberto_2', custom = {col = false, txd = 'objects/bases/4(blindado)/texture'}})
assignReplace(6924, {file = 'objects/bases/4(blindado)/12_porta', custom = {txd = 'objects/bases/4(blindado)/12_porta'}})
assignReplace(7599, {file = 'objects/bases/4(blindado)/13_teto', custom = {txd = 'objects/bases/4(blindado)/texture'}})
assignReplace(7507, {file = 'objects/bases/4(blindado)/14_teto_div', custom = {txd = 'objects/bases/4(blindado)/texture'}})
assignReplace(1486, {file = 'objects/bases/4(blindado)/15_teto_escada', custom = {txd = 'objects/bases/4(blindado)/texture'}})
assignReplace(2752, {file = 'objects/bases/4(blindado)/16_teto_triangular', custom = {txd = 'objects/bases/4(blindado)/texture'}})
